apps:
  ffmpeg-progress:
    command: 'bin/ffmpeg-progress'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/ffmpeg-progress/issues'
description: 'Get progress information for an ffmpeg process.'
grade: 'stable'
issues: 'https://github.com/Tatsh/ffmpeg-progress/issues'
license: 'MIT'
name: 'ffmpeg-progress'
parts:
  ffmpeg-progress:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/ffmpeg-progress'
summary: 'Get progress information for an ffmpeg process.'
title: 'ffmpeg-progress'
version: '0.0.6'
website: 'https://tatsh.github.io/ffmpeg-progress/'
